apiVersion: apps/v1
kind: Deployment
metadata:
  name: emergency-surge-frontend
  namespace: aks-mrgnc-surge-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emergency-surge-frontend
  template:
    metadata:
      labels:
        app: emergency-surge-frontend
    spec:
      containers:
        - name: emergency-surge-frontend
          image: acremergencysurge.azurecr.io/ng-mrgc-ui-image:prod-v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80